export const userConstants = {
    SEARCH_REQUEST: 'USERS_SEARCH_REQUEST',
    SEARCH_SUCCESS: 'USERS_SEARCH_SUCCESS',
    SEARCH_FAILURE: 'USERS_SEARCH_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',
};

export const httpStatus = {
    PROCESSING: 1,
    SUCCESS: 2,
    ERROR: 3
};